### PR TITLE
Add badges and license

### PR DESCRIPTION
**Pull request by JohanLorenzo**
I found out we didn't have a direct link to travis. I copied the badges from fxfox/foxbox. The coverage one is missing because coverage will require more investigation. 

r? @gmarty

### CODE REVIEW

**Comment by gmarty** [comment]
You need to update the license type in `package.json` too (the key is `"license"`).

**Comment by JohanLorenzo** [comment]
~~r? @gmarty~~ . I have a permafail on Travis. I currently don't see what could cause it. I also don't manage to repro.

I'll take a closer look at it, but I don't wanna waste your time, in the meantime

**Comment by gmarty** [comment]
In the latest master, @azasypkin fixed a race condition that affected the integration tests. See https://github.com/fxbox/app/pull/43#discussion_r58229896 for details.
Maybe your failure here is related to that.

**Comment by JohanLorenzo** [comment]
That seems to be it. Patch rebased r? @gm

**Pull request merged**
