### PR TITLE
Use latest taxonomy API + upgrade dependencies. r=gmarty

### PR DESCRIPTION
**Pull request by azasypkin**

### CODE REVIEW

**Comment by azasypkin** [comment]
r? @gmarty 

Foxbox has breaking changes, so here is the fix :)

**Comment by gmarty** [comment]
It looks good to me but as it touches the taxonomy I'm not really familiar with that'd be nice if someone else (like @Yoric) could have a quick look. r+
Thanks for updating the dependencies too!

**Comment by Yoric** [comment]
I'm not familiar with the code of the front-end, but what I see looks good.

Apologies for failing to announce the breaking changes properly, I had forgotten that you relied upon the format of this value.

**Comment by azasypkin** [comment]
Here is foxbox part of this PR https://github.com/fxbox/foxbox/pull/490 @gmarty @Yoric

**Comment by azasypkin** [comment]
https://github.com/fxbox/foxbox/pull/490 is merged, will merge this one as soon as I double check that everything works as expected (currently I can't start box :/)

**Comment by azasypkin** [comment]
Okay, checked with --disable-tls flag and everything looks good. Merging.

**Pull request merged**
